# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=50)),
                ('fax', models.CharField(default='', max_length=50)),
                ('web', models.CharField(default='', max_length=100)),
                ('categoria', models.CharField(default='', max_length=50)),
                ('subcategoria', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
