# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0003_alojamiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='latitude',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='longitude',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='numcomentarios',
            field=models.IntegerField(default=0),
        ),
    ]
