# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0005_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
