# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0006_comentario_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='language',
            field=models.CharField(default='', max_length=20),
        ),
    ]
