# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0007_alojamiento_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='img',
            field=models.URLField(default='', max_length=500),
        ),
    ]
