# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0008_alojamiento_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAñadido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(default='', max_length=100)),
                ('usuario', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_pagina',
            field=models.CharField(default='', max_length=100),
        ),
    ]
