# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0010_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='fecha',
            field=models.CharField(default='', max_length=100),
        ),
    ]
